// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5xxi2hOr6tHRFPFTmaBTf-3xDzbVUkOQ',
    appId: '1:349004421158:web:0a90d50ed696293dfaeee7',
    messagingSenderId: '349004421158',
    projectId: 'paco-86331',
    authDomain: 'paco-86331.firebaseapp.com',
    storageBucket: 'paco-86331.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFyi-yWQLLFkIWZ9zR7zDPzrv3UTi8wZo',
    appId: '1:349004421158:android:ff9779f79d23953dfaeee7',
    messagingSenderId: '349004421158',
    projectId: 'paco-86331',
    storageBucket: 'paco-86331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSo3XKVil2AuRLDuC3egQ_eIfVTFnahjo',
    appId: '1:349004421158:ios:0c79ed69b8db1c08faeee7',
    messagingSenderId: '349004421158',
    projectId: 'paco-86331',
    storageBucket: 'paco-86331.appspot.com',
    iosBundleId: 'com.example.pacoMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSo3XKVil2AuRLDuC3egQ_eIfVTFnahjo',
    appId: '1:349004421158:ios:27dc146a066dfc0afaeee7',
    messagingSenderId: '349004421158',
    projectId: 'paco-86331',
    storageBucket: 'paco-86331.appspot.com',
    iosBundleId: 'com.example.pacoMoney.RunnerTests',
  );
}
